export const SOCKET_EVENTS = {
  CREATE_ROOM: 'create-room',
  CREATED_ROOM: 'created-room',
  JOIN_ROOM: 'join-room',
  USER_JOINED: 'user-joined',
  SEND_VOTE: 'send-vote',
  VOTE_RECEIVED: 'vote-received',
  READY: 'ready',
  USER_READY: 'user-ready',
  READY_STATUS: 'ready-status',
  REVEAL_VOTES: 'reveal-votes',
  REVEALED: 'revealed',
  CREATE_STORY: 'create-story',
  CREATED_STORY: 'created-story',
  SELECT_STORY: 'select-story',
  SELECTED_STORY: 'selected-story',
  START_ESTIMATION: 'start-estimation',
  STARTED_ESTIMATION: 'started-estimation',
};
